package com.example.ui.strings

import com.example.data.repository.AppLanguage

object AppStrings {

    fun get(key: String, lang: AppLanguage): String {
        return when (lang) {
            AppLanguage.BENGALI -> BENGALI_STRINGS[key] ?: ENGLISH_STRINGS[key] ?: key
            AppLanguage.ARABIC -> ARABIC_STRINGS[key] ?: ENGLISH_STRINGS[key] ?: key
            AppLanguage.ENGLISH -> ENGLISH_STRINGS[key] ?: key
        }
    }

    private val ENGLISH_STRINGS = mapOf(
        "app_name" to "Noor Islam",
        "home" to "Home",
        "quran" to "Quran",
        "surah" to "Surah",
        "surahs" to "Surahs",
        "juz" to "Juz / Para",
        "juz_number" to "Juz %d",
        "bookmarks" to "Bookmarks",
        "last_read" to "Last Read",
        "search" to "Search",
        "prayer_times" to "Prayer Times",
        "prayer" to "Prayer",
        "settings" to "Settings",
        "continue_reading" to "Continue Reading",
        "next_prayer" to "Next Prayer",
        "in_time" to "in %s",
        "today" to "Today",
        "fajr" to "Fajr",
        "sunrise" to "Sunrise",
        "dhuhr" to "Dhuhr",
        "asr" to "Asr",
        "maghrib" to "Maghrib",
        "isha" to "Isha",
        "sehri" to "Sehri Ends",
        "iftar" to "Iftar",
        "tasbih" to "Tasbih",
        "qibla" to "Qibla",
        "names_of_allah" to "99 Names of Allah",
        "dua" to "Dua & Zikr",
        "digital_tasbih" to "Digital Tasbih Counter",
        "reset" to "Reset",
        "count" to "Count",
        "target" to "Target",
        "search_hint" to "Search Surah, Ayah number, or verse text...",
        "meccan" to "Meccan",
        "madinan" to "Madinan",
        "ayahs_count" to "%d Ayahs",
        "ayah_number" to "Ayah %d",
        "bismillah" to "بِسْمِ ٱللَّهِ ٱلرَّحْمَٰنِ ٱلرَّحِيمِ",
        "copy_ayah" to "Copy Ayah",
        "ayah_copied" to "Ayah copied to clipboard",
        "share_ayah" to "Share Ayah",
        "bookmark_added" to "Bookmark added",
        "bookmark_removed" to "Bookmark removed",
        "set_last_read" to "Set as Last Read",
        "no_bookmarks" to "No bookmarks saved yet",
        "no_bookmarks_desc" to "Tap the bookmark icon next to any Ayah while reading to save it here.",
        "search_results" to "Search Results",
        "no_results" to "No matching Surahs or Ayahs found",
        "interface_language" to "Interface Language",
        "select_language" to "Select Language",
        "quran_arabic_font_size" to "Arabic Script Size",
        "translation_font_size" to "Translation Font Size",
        "translation_display" to "Translation Display",
        "theme" to "Theme",
        "time_format" to "Time Format (12h / 24h)",
        "prayer_calculation_method" to "Prayer Calculation Method",
        "asr_calculation_method" to "Asr Juristic Method",
        "location" to "Location",
        "select_city" to "Select City",
        "detect_gps_location" to "Detect Current GPS Location",
        "notifications" to "Prayer Notifications",
        "data_verification" to "Quran Data Verification",
        "verified_status" to "114 Surahs & 6236 Ayahs Verified",
        "checksum" to "SHA-256 Checksum",
        "about" to "About Noor Islam",
        "about_desc" to "Noor Islam is an authentic, offline-first Islamic application featuring verified Uthmani script, authentic translations, precision prayer times, digital tasbih, and Islamic utilities.",
        "previous_surah" to "Previous Surah",
        "next_surah" to "Next Surah",
        "daily_verse" to "Verse of the Day",
        "quick_access" to "Quick Access",
        "page" to "Page",
        "manzil" to "Manzil",
        "ruku" to "Ruku"
    )

    private val BENGALI_STRINGS = mapOf(
        "app_name" to "নূর ইসলাম",
        "home" to "হোম",
        "quran" to "কুরআন",
        "surah" to "সূরা",
        "surahs" to "সূরা সমূহ",
        "juz" to "পারা / জুয",
        "juz_number" to "%d নং পারা",
        "bookmarks" to "বুকমার্ক",
        "last_read" to "সর্বশেষ পঠিত",
        "search" to "অনুসন্ধান",
        "prayer_times" to "নামাজের সময়সূচি",
        "prayer" to "নামাজ",
        "settings" to "সেটিংস",
        "continue_reading" to "পড়া চালিয়ে যান",
        "next_prayer" to "পরবর্তী ওয়াক্ত",
        "in_time" to "%s পর",
        "today" to "আজ",
        "fajr" to "ফজর",
        "sunrise" to "সূর্যোদয়",
        "dhuhr" to "যোহর",
        "asr" to "আসর",
        "maghrib" to "মাগরিব",
        "isha" to "ইশা",
        "sehri" to "সেহরি শেষ",
        "iftar" to "ইফতার",
        "tasbih" to "তসবিহ",
        "qibla" to "কিবলা",
        "names_of_allah" to "আল্লাহর ৯৯ নাম",
        "dua" to "দোয়া ও জিকির",
        "digital_tasbih" to "ডিজিটাল তসবিহ গণক",
        "reset" to "রিসেট",
        "count" to "গণনা",
        "target" to "টার্গেট",
        "search_hint" to "সূরা, আয়াত নম্বর বা আয়াত খুঁজুন...",
        "meccan" to "মাক্কী",
        "madinan" to "মাদানী",
        "ayahs_count" to "%d টি আয়াত",
        "ayah_number" to "আয়াত %d",
        "bismillah" to "بِسْمِ ٱللَّهِ ٱلرَّحْمَٰنِ ٱلرَّحِيمِ",
        "copy_ayah" to "আয়াত কপি করুন",
        "ayah_copied" to "আয়াত ক্লিপবোর্ডে কপি হয়েছে",
        "share_ayah" to "আয়াত শেয়ার করুন",
        "bookmark_added" to "বুকমার্ক যুক্ত হয়েছে",
        "bookmark_removed" to "বুকমার্ক সরানো হয়েছে",
        "set_last_read" to "সর্বশেষ পঠিত হিসেবে চিহ্নিত করুন",
        "no_bookmarks" to "কোনো বুকমার্ক সংরক্ষিত নেই",
        "no_bookmarks_desc" to "কুরআন পড়ার সময় আয়াতের বুকমার্ক আইকনে ট্যাপ করে এখানে সংরক্ষণ করুন।",
        "search_results" to "অনুসন্ধানের ফলাফল",
        "no_results" to "কোনো মিল খুঁজে পাওয়া যায়নি",
        "interface_language" to "অ্যাপের ভাষা",
        "select_language" to "ভাষা নির্বাচন করুন",
        "quran_arabic_font_size" to "আরবি লেখার সাইজ",
        "translation_font_size" to "অনুবাদ লেখার সাইজ",
        "translation_display" to "অনুবাদ নির্বাচন",
        "theme" to "থিম",
        "time_format" to "সময় ফরম্যাট (১২/২৪ ঘণ্টা)",
        "prayer_calculation_method" to "নামাজ গণনার পদ্ধতি",
        "asr_calculation_method" to "আসর গণনার মাজহাব",
        "location" to "অবস্থান",
        "select_city" to "শহর নির্বাচন করুন",
        "detect_gps_location" to "বর্তমান জিপিএস লোকেশন শনাক্ত করুন",
        "notifications" to "নামাজের নোটিফিকেশন",
        "data_verification" to "কুরআন ডেটা সত্যতা যাচাই",
        "verified_status" to "১১৪টি সূরা এবং ৬২৩৬টি আয়াত সম্পূর্ণ যাচাইকৃত",
        "checksum" to "SHA-256 চেকসাম",
        "about" to "নূর ইসলাম পরিচিতি",
        "about_desc" to "নূর ইসলাম একটি নির্ভুল, অফলাইন ইসলামিক অ্যাপ। এতে রয়েছে মূল উসমানি লিপি, সঠিক অনুবাদ, নিখুঁত নামাজের সময়সূচি, সেহরি-ইফতার কাউন্টডাউন ও অন্যান্য ইসলামিক সেবা।",
        "previous_surah" to "পূর্ববর্তী সূরা",
        "next_surah" to "পরবর্তী সূরা",
        "daily_verse" to "আজকের আয়াত",
        "quick_access" to "কুইক এক্সেস",
        "page" to "পৃষ্ঠা",
        "manzil" to "মঞ্জিল",
        "ruku" to "রুকু"
    )

    private val ARABIC_STRINGS = mapOf(
        "app_name" to "نور الإسلام",
        "home" to "الرئيسية",
        "quran" to "القرآن",
        "surah" to "سورة",
        "surahs" to "السور",
        "juz" to "الأجزاء",
        "juz_number" to "الجزء %d",
        "bookmarks" to "العلامات المرجعية",
        "last_read" to "آخر قراءة",
        "search" to "البحث",
        "prayer_times" to "مواقيت الصلاة",
        "prayer" to "الصلاة",
        "settings" to "الإعدادات",
        "continue_reading" to "متابعة القراءة",
        "next_prayer" to "الصلاة القادمة",
        "in_time" to "خلال %s",
        "today" to "اليوم",
        "fajr" to "الفجر",
        "sunrise" to "الشروق",
        "dhuhr" to "الظهر",
        "asr" to "العصر",
        "maghrib" to "المغرب",
        "isha" to "العشاء",
        "sehri" to "إمساك السحور",
        "iftar" to "الإفطار",
        "tasbih" to "التسبيح",
        "qibla" to "القبلة",
        "names_of_allah" to "أسماء الله الحسنى",
        "dua" to "الأدعية والأذكار",
        "digital_tasbih" to "السبحة الإلكترونية",
        "reset" to "إعادة ضبط",
        "count" to "العدد",
        "target" to "الهدف",
        "search_hint" to "ابحث عن سورة، رقم آية، أو نص...",
        "meccan" to "مكية",
        "madinan" to "مدنية",
        "ayahs_count" to "%d آيات",
        "ayah_number" to "آية %d",
        "bismillah" to "بِسْمِ ٱللَّهِ ٱلرَّحْمَٰنِ ٱلرَّحِيمِ",
        "copy_ayah" to "نسخ الآية",
        "ayah_copied" to "تم نسخ الآية إلى الحافظة",
        "share_ayah" to "مشاركة الآية",
        "bookmark_added" to "تمت إضافة العلامة المرجعية",
        "bookmark_removed" to "تمت إزالة العلامة المرجعية",
        "set_last_read" to "تعيين كآخر قراءة",
        "no_bookmarks" to "لا توجد علامات مرجعية محفوظة",
        "no_bookmarks_desc" to "انقر على رمز العلامة المرجعية أثناء القراءة لحفظ الآية هنا.",
        "search_results" to "نتائج البحث",
        "no_results" to "لم يتم العثور على نتائج مطابقة",
        "interface_language" to "لغة الواجهة",
        "select_language" to "اختيار اللغة",
        "quran_arabic_font_size" to "حجم الخط العربي",
        "translation_font_size" to "حجم خط الترجمة",
        "translation_display" to "عرض الترجمة",
        "theme" to "المظهر",
        "time_format" to "صيغة الوقت (١٢ / ٢٤ ساعة)",
        "prayer_calculation_method" to "طريقة حساب المواقيت",
        "asr_calculation_method" to "مذهب حساب العصر",
        "location" to "الموقع",
        "select_city" to "اختيار المدينة",
        "detect_gps_location" to "تحديد الموقع الحالي عبر GPS",
        "notifications" to "تنبيهات الصلاة",
        "data_verification" to "التحقق من بيانات القرآن",
        "verified_status" to "١١٤ سورة و ٦٢٣٦ آية موثقة ومعتمدة",
        "checksum" to "رمز التحقق SHA-256",
        "about" to "عن نور الإسلام",
        "about_desc" to "نور الإسلام تطبيق إسلامي موثق يعمل بدون إنترنت بالنص العثماني ومواقيت الصلاة الفلكية الدقيقة والسبحة الإلكترونية ومختلف الخدمات الإسلامية.",
        "previous_surah" to "السورة السابقة",
        "next_surah" to "السورة التالية",
        "daily_verse" to "آية اليوم",
        "quick_access" to "وصول سريع",
        "page" to "صفحة",
        "manzil" to "منزل",
        "ruku" to "ركوع"
    )
}
